---
title: "date_windows"
output: 
  html_document:
    toc: TRUE
date: "2023-09-19"
---

```{r, include = F}
require(tidyverse)
require(sf)
```

# CalMapper
```{r}
load( file = "Rdata/CalMapper_activities_fire_noNF.Rdata")
```

```{r}
summary(as.factor(cm$YEAR))
```

```{r}
total_acres <- cm %>% 
  st_drop_geometry() %>% 
  summarize(total_acres = sum(TREATED_ACRES)) %>% 
  unlist() 
total_acres
total <- cm %>% 
  st_drop_geometry() %>% 
  count() %>% 
  unlist()
total
```

## Duration of NA
```{r}
cm %>% 
  st_drop_geometry() %>% 
  filter(is.na(DURATION)) %>% 
  count()%>% 
  mutate(percent = round(n/total, 2)*100)
```


## One day
```{r}
cm %>% 
  st_drop_geometry() %>% 
  filter(DURATION == 1) %>% 
  count()%>% 
  mutate(percent = round(n/total, 2)*100)
```

```{r}
cm %>% 
  st_drop_geometry() %>% 
  filter(DURATION == 1) %>% 
  summarize(ac = sum(TREATED_ACRES))%>% 
  mutate(percent = round(ac/total_acres, 2)*100)
```


## Two days
```{r}
cm %>% 
  st_drop_geometry() %>% 
  filter(DURATION == 2) %>% 
  count()%>% 
  mutate(percent = round(n/total, 2)*100)
```

```{r}
cm %>% 
  st_drop_geometry() %>% 
  filter(DURATION == 2) %>% 
  summarize(ac = sum(TREATED_ACRES))%>% 
  mutate(percent = round(ac/total_acres, 2)*100)
```

## 3-7 days
```{r}
cm %>% 
  st_drop_geometry() %>% 
  filter(DURATION  > 2 & DURATION < 8) %>% 
  count()%>% 
  mutate(percent = round(n/total, 2)*100)
```

```{r}
cm %>% 
  st_drop_geometry() %>% 
  filter(DURATION  > 2 & DURATION < 8) %>% 
  summarize(ac = sum(TREATED_ACRES))%>% 
  mutate(percent = round(ac/total_acres, 2)*100)
```

## 8 to 31 days
```{r}
cm %>% 
  st_drop_geometry() %>% 
  filter(DURATION  > 7 & DURATION < 32) %>% 
  count()%>% 
  mutate(percent = round(n/total, 2)*100)
```

```{r}
cm %>% 
  st_drop_geometry() %>% 
  filter(DURATION  > 7 & DURATION < 32) %>% 
  summarize(ac = sum(TREATED_ACRES))%>% 
  mutate(percent = round(ac/total_acres, 2)*100)
```

## More than 31 days
```{r}
cm %>% 
  st_drop_geometry() %>% 
  filter(DURATION  > 31) %>% 
  count() %>% 
  mutate(percent = round(n/total, 2)*100)
```

```{r}
cm %>% 
  st_drop_geometry() %>% 
  filter(DURATION  > 31) %>% 
  summarize(ac = sum(TREATED_ACRES))%>% 
  mutate(percent = round(ac/total_acres, 2)*100)
```


```{r}
cm %>% 
  st_drop_geometry() %>% 
  group_by(DURATION) %>% 
  count() %>% 
  ungroup() %>% 
  mutate(percent = (n/sum(n)*100 )) %>% 
  print()
```



```{r}
ggplot(cm)+
  geom_histogram(aes(log(as.numeric(DURATION))), fill = "#00ba38")+
  theme_minimal()+
  xlab("Duration (days)")+
  scale_x_continuous(breaks = c(0, 2.3, 4.6, 6.9), labels = c("1", "10", "100", "1000"))
```


```{r}
ggsave("figures/calmapper_duration.png", width = 3, height = 2)
```

```{r}
cm %>% 
  st_drop_geometry() %>% 
  group_by(DURATION) %>% 
  count() %>% 
  ungroup() %>% 
  mutate(percent = (n/sum(n)*100 )) %>% 
  arrange(desc(percent)) %>% 
  print()
```



## Define path to Calmapper and to the gdb file
```{r}
calmapper_dir <- fs::dir_ls(ref_path, recurse = T, glob = '*CalMAPPER', type = 'directory')
calmapper_gdb <- fs::dir_ls(calmapper_dir, recurse = T, glob = '*.gdb')
if(length(calmapper_gdb) > 1){
  stop( "There's more than one CalMAPPER .gdb file. script assumes only 1.")
}

```

```{r}
st_layers(calmapper_gdb)
trt <- st_read(calmapper_gdb, layer = 'CMDash_TreatmentPols')
```

```{r}
trt <- trt %>% 
  mutate(DURATION = PROJECT_END_DATE - PROJECT_START_DATE + 1)
```


```{r}
ggplot(trt)+
  geom_histogram(aes(log(as.numeric(DURATION))), fill = "#00ba38")+
  theme_minimal()+
  xlab("Duration (days)")+
  scale_x_continuous(breaks = c(0, 2.3, 4.6, 6.9), labels = c("1", "10", "100", "1,000"))
```



```{r}
ggplot(trt)+
  geom_histogram(aes(DURATION), fill = "#00ba38")+
  theme_minimal()+
  xlab("Duration (days)")+
  scale_x_continuous(breaks = c(1,10,100,1000), labels = c("1", "10", "100", "1,000"))
```

# FRAP

## Load data
```{r}
file <- paste(ref_path, "/FRAP fire perimeters/frap_Rx_fire_2017-2022.Rdata", sep = "")
load(file)
```

```{r}
head(frap)
```

```{r}
frap <- frap %>% 
  mutate(Duration = END_DATE - START_DATE + 1)
```

```{r}
frap %>% 
  st_drop_geometry() %>% 
  group_by(Duration) %>% 
  count() %>% 
  ungroup() %>% 
  mutate(percent = (n/sum(n)*100 )) %>% 
  print()
```


```{r}
frap %>% 
  st_drop_geometry() %>% 
  filter(Duration>1) %>% 
  count() 
```

```{r}
summary(as.factor(frap$Duration))
```

```{r}
frap %>% st_drop_geometry() %>% count()
```

```{r}
frap %>% 
  filter(is.na(Duration)) %>% 
  tail()
```


```{r}
ggplot(frap)+
  geom_histogram(aes(log(as.numeric(Duration))), fill = "#ee936b")+
  theme_minimal()+
  xlab("Duration (days)")+
  scale_x_continuous(breaks = c(0, 2.3, 4.6, 6.9), labels = c("1", "10", "100", "1000"))
  
```



```{r}
ggsave("figures/frap_duration.png", width = 3, height = 2)
```
