---
title: "CalMAPPER"
output: 
  html_document:
    toc: TRUE
date: '2022-07-26'
editor_options: 
  chunk_output_type: console
---

```{r, include = F}
require(tidyverse)
require(lubridate)
require(sf)
require(fs)
```

# Description

This script merges CalMAPPER activity data with treatment polygons. This is a necessary step before analyzing prescribed fire data in CalMAPPER. 

```{r}

# define path to Calmapper and to the gdb file
calmapper_dir <- fs::dir_ls(ref_path, recurse = T, glob = '*CalMAPPER', type = 'directory')
calmapper_files <- fs::dir_ls(calmapper_dir, recurse = T, glob = '*.gdb')
if(length(calmapper_files) > 1){
  stop( "There's more than one CalMAPPER .gdb file. script assumes only 1.")
}

```


```{r}
st_layers(calmapper_files)
act <- st_read(calmapper_files, layer = 'CMDash_Activities')
trt <- st_read(calmapper_files, layer = 'CMDash_TreatmentPols')
```


# Clean
## Remove non-treatment "activities"
```{r}
act <- act %>% 
  filter(!ACTIVITY_DESCRIPTION %in% c("GIS Validation", "Education Outreach", "Project Administration", "Planning Meeting", "Public Contacts", "Water Site Development"))
```

## Fix date format

### Activities
```{r}
act <- act %>% 
  mutate(ACTIVITY_START_date =  as.Date(ACTIVITY_START, format = "%m/%d/%Y")) %>% 
  mutate(PROJECT_START_DATE_date =  as.Date(ACTIVITY_END, format = "%m/%d/%Y")) 
```

```{r}
act <- act %>% 
  mutate(ACTIVITY_START_date = if_else(is.na(ACTIVITY_START_date), PROJECT_START_DATE_date, ACTIVITY_START_date))
```

## Treatments

# Sort by acreage
```{r}
act %>% 
  filter(ACTIVITY_START_date > "2020-01-01" & ACTIVITY_START_date < "2020-12-31") %>% 
  group_by(ACTIVITY_DESCRIPTION) %>% 
  summarize(acres = sum(TREATED_ACRES)) %>% 
  arrange(desc(acres)) %>% 
  print(n = 35)
```

# Merge Rx fire Activity data with treatment polygons
```{r}
# join act with trt to get geometry. use projectID, treatmentID
act_sf <- right_join(trt %>% select(PROJECT_ID, TREATMENT_ID), 
           act)

# clean up the data
act_sf <- act_sf[!st_is_empty(act_sf),] # remove empties
```

# Save

```{r}
#dsn <- file.path(calmapper_dir, "shapefiles")
#st_write(act_sf, dsn = dsn, layer = "trt_act", driver = "ESRI Shapefile", delete_layer = T)
```

```{r}
# I've always saved .rds files instead... .Rdata loads the workspace???
# save(act_sf, file = file.path(calmapper_dir, "treatment-activities.Rdata") )
write_rds(act_sf, file = file.path(calmapper_dir, "treatment-activities.rds"))

```

```{r}
write_csv(act_sf %>% st_drop_geometry(), 
          file = file.path(calmapper_dir, "activities.csv"))
          
write_csv(trt %>% st_drop_geometry(),
          file = file.path(calmapper_dir, "treatments.csv"))
```
